tests(http): full bats with assert
infinyon/fluvio-connectors pull request #138
Opened 2022-02-01 09:05 UTC by pinkforest

**CI Integration test for http full**

- Paying off the claimed techdebt from 
#127 
- Further CD compatible integration tests to be worked on:
#134 

**Notes**

I had to add bats's bats assert and support libs in order to make this work.

Otherwise it is painful to deal with multi-line in bats bash.

The sleep x probably needs refactoring to instead ensure the topic is ready and consumable

I wanted initially to use a regex initially with assert_output --regex and load the regex from a file but bash strips any newlines and read -rd '' doesn't work with bats for some reason.

So instead of regex I settled with assert_output --partial

get-test-full.regex
```
^HTTP/1.1 200 OK
content-length: \d+
content-type: text/plain;charset=utf-8
date: [A-Za-z]+, \d+ [A-Za-z]+ \d+ \d+:\d+:\d+ [A-Z]+

Hello, Fluvio! - \d+$
```

2022-02-01 19:46 UTC, simlay requested changes
Let's move the helpers `rust-connectors/sources/http/tests/libs` to maybe `rust-connectors/utils/bats-libs` or something.

2022-02-02 19:22 UTC, pinkforest commented
Moved them to ../../../utils/bats-helpers

2022-02-02 19:26 UTC, simlay approved these changes
LGTM! Thanks!

2022-02-02 19:26 UTC, simlay commented
bors r+

2022-02-02 19:29 UTC, simlay commented
bors r+

2022-02-02 20:12 UTC, simlay commented
bors retry

2022-02-02 20:30 UTC, closed without merging